# Generated by Django 4.2.6 on 2025-03-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='videos/%Y/%m/', verbose_name='视频地址'),
        ),
    ]
