# Generated by Django 4.2.6 on 2025-03-29 12:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='上传合辑封面图', null=True, upload_to=core.models.collection_thumb_path, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='上传视频缩略图', null=True, upload_to=core.models.video_thumb_path, verbose_name='缩略图'),
        ),
    ]
